import { SyncSessionService } from "../../src/modules/low-connectivity/sync-session.service";
import { LowConnectivityAuthorizationService } from "../../src/modules/low-connectivity/low-connectivity.authorization";
import { PacketHandlerRegistry } from "../../src/modules/low-connectivity/packet-handler.registry";
import { InMemoryLowConnectivitySyncRepository } from "../testUtils/inMemoryLowConnectivitySyncRepository";
import { AuthenticatedUserContext } from "../../src/modules/auth/auth.types";

const user: AuthenticatedUserContext = { id:"u1", publicId:"u-public", role:"FARMER" };
function setup(handlerThrows=false){const repo=new InMemoryLowConnectivitySyncRepository();const registry=new PacketHandlerRegistry();let calls=0;registry.register({targetModule:"SYSTEM",action:"PING",handle:async()=>{calls++;if(handlerThrows)throw new Error("boom");return {ok:true};}});const service=new SyncSessionService(repo,registry,new LowConnectivityAuthorizationService());return {repo,service,get calls(){return calls;}};}

describe("SyncSessionService",()=>{
 test("starts idempotently and accepts ordered packets",async()=>{const x=setup();const s1=await x.service.startSession(user,{deviceId:"phone"});const s2=await x.service.startSession(user,{deviceId:"phone"});expect(s2.id).toBe(s1.id);await x.service.submitPacket(user,s1.publicId,{sequence:1,idempotencyKey:"abcdefgh",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()});const p2=await x.service.submitPacket(user,s1.publicId,{sequence:2,idempotencyKey:"ijklmnop",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()});expect(p2.status).toBe("APPLIED");expect(x.calls).toBe(2);});
 test("rejects out of order and idempotent resubmission does not rerun handler",async()=>{const x=setup();const s=await x.service.startSession(user,{deviceId:"phone"});await expect(x.service.submitPacket(user,s.publicId,{sequence:2,idempotencyKey:"abcdefgh",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()})).rejects.toMatchObject({code:"SYNC_PACKET_OUT_OF_ORDER",statusCode:409});const p=await x.service.submitPacket(user,s.publicId,{sequence:1,idempotencyKey:"abcdefgh",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()});const same=await x.service.submitPacket(user,s.publicId,{sequence:99,idempotencyKey:"abcdefgh",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()});expect(same.id).toBe(p.id);expect(x.calls).toBe(1);});
 test("failed packet advances sequence and retry creates a new packet",async()=>{const x=setup(true);const s=await x.service.startSession(user,{deviceId:"phone"});const failed=await x.service.submitPacket(user,s.publicId,{sequence:1,idempotencyKey:"abcdefgh",targetModule:"SYSTEM",action:"PING",payload:{},clientCreatedAt:new Date()});expect(failed.status).toBe("FAILED");expect((await x.service.getStatus(user,s.publicId)).session.lastAppliedSequence).toBe(1);const retried=await x.service.retryPacket(user,s.publicId,failed.publicId);expect(retried.sequence).toBe(2);});
});
